# Generated by Django 5.2.17 on 2026-09-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("URGENT", "긴급"), ("NORMAL", "일반")],
                        default="NORMAL",
                        help_text="공지 유형 (URGENT: 긴급, NORMAL: 일반)",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(help_text="공지 제목", max_length=200)),
                ("content", models.TextField(help_text="공지 본문")),
                (
                    "image_url",
                    models.CharField(
                        blank=True, help_text="첨부 사진 URL", max_length=500, null=True
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="작성 관리자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="admins.admin",
                    ),
                ),
            ],
            options={
                "db_table": "notice",
                "ordering": ["-created_at"],
            },
        ),
    ]
