# Generated by Django 5.2.17 on 2026-09-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "place_type",
                    models.CharField(
                        choices=[("BOOTH", "부스"), ("FACILITY", "시설")], max_length=20
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TOILET", "화장실"),
                            ("ALCOHOL", "주점"),
                            ("COLLAB", "협업"),
                            ("ECO", "동빛에코"),
                            ("ETC", "부스"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("zone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "location_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "map_x",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "map_y",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "map_elevation",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "rotation",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("entrance_fee", models.IntegerField(blank=True, null=True)),
                ("event_description", models.TextField(blank=True, null=True)),
                (
                    "instagram_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("has_reusable_container", models.BooleanField(default=True)),
                ("directions", models.TextField(blank=True, null=True)),
                ("lantern_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BoothMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("sort_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="booths.booth",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="BoothOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festival_date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(choices=[("DAY", "주간"), ("NIGHT", "야간")], max_length=10),
                ),
                ("open_at", models.TimeField()),
                ("close_at", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="booths.booth",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booth", "festival_date", "time_slot"),
                        name="unique_booth_operation_slot",
                    )
                ],
            },
        ),
    ]
