# Generated by Django 5.2.17 on 2026-09-16 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyCouponCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WinningNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("coupon_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("issued_date", models.DateField()),
                ("daily_sequence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNSCRATCHED", "미긁음"),
                            ("WIN", "당첨"),
                            ("LOSE", "꽝"),
                            ("USED", "사용 완료"),
                            ("EXPIRED", "기간 만료"),
                        ],
                        default="UNSCRATCHED",
                        max_length=20,
                    ),
                ),
                ("scratched_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="coupons.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issued_date", "daily_sequence"),
                        name="unique_daily_coupon_sequence",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "issued_date"), name="unique_daily_coupon_per_user"
                    ),
                ],
            },
        ),
    ]
