# Generated by Django 6.0.5 on 2026-09-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booths", "0001_initial"),
        ("coupons", "0004_coupon_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boothverifycode",
            name="booth_name",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="used_booth_name",
        ),
        migrations.AddField(
            model_name="boothverifycode",
            name="booth",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verify_code_entry",
                to="booths.booth",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_booth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_coupons",
                to="booths.booth",
            ),
        ),
    ]
