# Generated by Django 6.0.5 on 2026-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0005_remove_boothverifycode_booth_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boothverifycode",
            name="booth",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="used_booth",
        ),
        migrations.AddField(
            model_name="boothverifycode",
            name="location_label",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_location_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
