# Generated by Django 6.0.5 on 2026-09-20 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0006_remove_boothverifycode_booth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boothverifycode",
            name="location_label",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="used_location_label",
        ),
    ]
