# Generated by Django 5.2.17 on 2026-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_key",
                    models.CharField(
                        help_text="관리자 키(해시 저장) / 관리자 인증", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="관리자 구분명", max_length=30, null=True
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, help_text="마지막 접속 시각", null=True),
                ),
            ],
            options={
                "db_table": "admin",
                "ordering": ["-created_at"],
            },
        ),
    ]
