# Generated by Django 5.2.17 on 2026-09-18 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("booths", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lantern",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(default="익명의 코끼리", max_length=10)),
                ("message", models.CharField(max_length=30)),
                ("festival_date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        choices=[("USER", "사용자"), ("ADMIN", "관리자")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanterns",
                        to="booths.booth",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanterns",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanternReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ABUSE", "욕설 및 비방"),
                            ("FALSE_INFO", "허위정보"),
                            ("OBSCENE", "음란·불쾌"),
                            ("ETC", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "lantern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lantern_reports",
                        to="lanterns.lantern",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lantern_reports",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lantern",
            index=models.Index(fields=["user", "festival_date"], name="idx_lantern_user_date"),
        ),
        migrations.AddIndex(
            model_name="lantern",
            index=models.Index(fields=["booth", "deleted_at"], name="idx_lantern_booth_deleted"),
        ),
        migrations.AddConstraint(
            model_name="lantern",
            constraint=models.UniqueConstraint(
                fields=("user", "booth", "festival_date"), name="unique_user_booth_lantern_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="lanternreport",
            constraint=models.UniqueConstraint(
                fields=("lantern", "user"), name="unique_lantern_user_report"
            ),
        ),
    ]
